title: Dictionary of Geneseo English
description: A dictionary of local terms built by SUNY Geneseo students under the direction of Prof. Graham Drake
theme: just-the-docs

# url: https://cdl-geneseo.github.io/geneseo-dictionary

# aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
